import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// auth params (from rapid api "options")
const cryptoApiHeaders = {
  "x-rapidapi-host": "coinranking1.p.rapidapi.com",
  "x-rapidapi-key": "0cec8cc5b7msh2c9ac898334a653p17419djsn75d51e56e769",
};

// func to pass both the "HEADERS" to the api query
const createRequest = (url) => ({ url, headers: cryptoApiHeaders });

// all endpoints for CRYPTO API is fed here
export const cryptoApi = createApi({
  reducerPath: "cryptoApi",
  baseQuery: fetchBaseQuery({
    baseUrl: "https://coinranking1.p.rapidapi.com",
  }),
  endpoints: (builder) => ({
    getCryptoCoins: builder.query({
      query: (coinCount) => createRequest(`/coins?limit=${coinCount}`),
    }),
    getCoinDetails: builder.query({
      query: (coinId) => createRequest(`/coin/${coinId}`),
    }),
    getCoinHistory: builder.query({
      query: ({ coinId, timePeriod }) =>
        createRequest(`/coin/${coinId}/history/${timePeriod}`),
    }),
  }),
});

// this hook is automatically generated by RTK
export const {
  useGetCryptoCoinsQuery,
  useGetCoinDetailsQuery,
  useGetCoinHistoryQuery,
} = cryptoApi;
